"""
SSDLC ANALYZER — EXECUTIVE SECURITY ASSESSMENT REPORT GENERATOR
Redesigned PDF Report Generator built with ReportLab.

Establishes an executive-grade document art direction:
- Strict A4 portrait document grid (43.2 pt margins)
- Two-pass NumberedCanvas for dynamic "Page X of Y" headers & footers
- Minimal editorial cover page with thin rules and restrained typography
- Table of Contents
- Editorial horizontal posture scale (0 - 25 - 50 - 75 - 100)
- Single aligned domain assessment table with repeating headers
- Uniform finding blocks with stable IDs (F-001, F-002...)
- Monospace technical evidence blocks
- Passed controls, Skipped controls, Manual verification audit notes
- Prioritized remediation roadmap and professional methodology/limitations
"""

import io
import datetime
from typing import Dict, Any, List

from reportlab.lib.pagesizes import letter
from reportlab.lib import colors
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.platypus import (
    SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle, PageBreak, KeepTogether, HRFlowable
)
from reportlab.pdfgen import canvas


class NumberedCanvas(canvas.Canvas):
    """
    Two-pass canvas to compute total page count dynamically
    and render running headers and footers ("Page X of Y").
    """
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self._saved_page_states = []

    def showPage(self):
        self._saved_page_states.append(dict(self.__dict__))
        self._startPage()

    def save(self):
        num_pages = len(self._saved_page_states)
        for state in self._saved_page_states:
            self.__dict__.update(state)
            self.draw_page_decorations(num_pages)
            canvas.Canvas.showPage(self)
        canvas.Canvas.save(self)

    def draw_page_decorations(self, page_count):
        # Skip header and footer on Cover Page (Page 1)
        if self._pageNumber == 1:
            return

        self.saveState()
        self.setFont("Helvetica-Bold", 7.5)
        self.setFillColor(colors.HexColor("#475569"))

        # Running Header
        self.drawString(43.2, 804, "SSDLC ANALYZER")
        self.setFont("Helvetica", 7.5)
        self.drawString(125, 804, "|   Security Assessment Report")
        self.drawRightString(552, 804, "CONFIDENTIAL / INTERNAL TECHNICAL USE")
        self.setStrokeColor(colors.HexColor("#CBD5E1"))
        self.setLineWidth(0.5)
        self.line(43.2, 796, 552, 796)

        # Running Footer
        self.line(43.2, 45, 552, 45)
        self.setFont("Helvetica", 7.5)
        self.drawString(43.2, 32, "Generated by SSDLC Analyzer Engine v2.0.0")
        self.drawRightString(552, 32, f"Page {self._pageNumber} of {page_count}")
        self.restoreState()


def get_risk_classification(score: float) -> Dict[str, str]:
    if score >= 80:
        return {"label": "LOW RISK", "color": "#15803D", "desc": "Security controls demonstrate strong baseline maturity."}
    elif score >= 60:
        return {"label": "MODERATE RISK", "color": "#B45309", "desc": "Multiple security controls require technical remediation."}
    elif score >= 40:
        return {"label": "HIGH RISK", "color": "#C2410C", "desc": "Significant security posture gaps identified across key domains."}
    else:
        return {"label": "CRITICAL RISK", "color": "#B91C1C", "desc": "Urgent remediation required to address core security failures."}


def get_domain_status(score_pct: float) -> Dict[str, str]:
    if score_pct >= 80:
        return {"label": "STRONG", "color": "#15803D"}
    elif score_pct >= 60:
        return {"label": "ADEQUATE", "color": "#1D4ED8"}
    elif score_pct >= 40:
        return {"label": "NEEDS IMPROVEMENT", "color": "#B45309"}
    else:
        return {"label": "WEAK", "color": "#B91C1C"}


def format_text(text: str) -> str:
    if not text:
        return ""
    return str(text).replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;")


def generate_pdf_report(scan_data: Dict[str, Any]) -> bytes:
    """
    Generates an executive-grade PDF security assessment report from scan data.
    """
    buffer = io.BytesIO()
    doc = SimpleDocTemplate(
        buffer,
        pagesize=letter,
        leftMargin=43.2,
        rightMargin=43.2,
        topMargin=54,
        bottomMargin=54,
    )

    styles = getSampleStyleSheet()

    # Editorial Typography Styles
    doc_title_style = ParagraphStyle(
        'DocTitle',
        parent=styles['Normal'],
        fontName='Helvetica-Bold',
        fontSize=22,
        leading=26,
        textColor=colors.HexColor('#0F172A'),
        spaceAfter=4,
    )

    doc_subtitle_style = ParagraphStyle(
        'DocSubtitle',
        parent=styles['Normal'],
        fontName='Helvetica',
        fontSize=11,
        leading=15,
        textColor=colors.HexColor('#475569'),
        spaceAfter=12,
    )

    section_num_style = ParagraphStyle(
        'SectionNum',
        parent=styles['Normal'],
        fontName='Helvetica-Bold',
        fontSize=9,
        leading=11,
        textColor=colors.HexColor('#64748B'),
        spaceBefore=14,
        spaceAfter=2,
        keepWithNext=True,
    )

    h1_style = ParagraphStyle(
        'Heading1_Editorial',
        parent=styles['Heading1'],
        fontName='Helvetica-Bold',
        fontSize=14,
        leading=18,
        textColor=colors.HexColor('#0F172A'),
        spaceBefore=2,
        spaceAfter=8,
        keepWithNext=True,
    )

    h2_style = ParagraphStyle(
        'Heading2_Editorial',
        parent=styles['Heading2'],
        fontName='Helvetica-Bold',
        fontSize=11,
        leading=15,
        textColor=colors.HexColor('#1E293B'),
        spaceBefore=8,
        spaceAfter=4,
        keepWithNext=True,
    )

    body_style = ParagraphStyle(
        'Body_Editorial',
        parent=styles['Normal'],
        fontName='Helvetica',
        fontSize=9,
        leading=13,
        textColor=colors.HexColor('#334155'),
        spaceAfter=6,
    )

    body_bold = ParagraphStyle(
        'BodyBold_Editorial',
        parent=body_style,
        fontName='Helvetica-Bold',
    )

    mono_style = ParagraphStyle(
        'Mono_Editorial',
        parent=styles['Normal'],
        fontName='Courier',
        fontSize=8,
        leading=11,
        textColor=colors.HexColor('#0F172A'),
        backColor=colors.HexColor('#F8FAFC'),
        borderColor=colors.HexColor('#E2E8F0'),
        borderWidth=0.5,
        borderPadding=6,
        spaceBefore=4,
        spaceAfter=6,
    )

    tbl_head_style = ParagraphStyle(
        'TblHeader',
        parent=styles['Normal'],
        fontName='Helvetica-Bold',
        fontSize=8.5,
        leading=11,
        textColor=colors.HexColor('#0F172A'),
    )

    tbl_cell_style = ParagraphStyle(
        'TblCell',
        parent=styles['Normal'],
        fontName='Helvetica',
        fontSize=8.5,
        leading=11.5,
        textColor=colors.HexColor('#334155'),
    )

    story = []

    # Extract Data
    project_name = scan_data.get('project', 'Repository')
    summary = scan_data.get('summary', {})
    score = float(summary.get('score', 0))
    risk_info = get_risk_classification(score)
    domains = scan_data.get('domains', [])
    findings = scan_data.get('findings', [])
    started_at = scan_data.get('started_at', datetime.datetime.now().strftime("%Y-%m-%d %H:%M:%S"))
    scan_id = scan_data.get('scan_id', 'N/A')

    passed_findings = [f for f in findings if f.get('status') == 'PASS']
    failed_findings = [f for f in findings if f.get('status') in ['FAIL', 'ERROR']]
    skipped_findings = [f for f in findings if f.get('status') == 'SKIPPED']
    manual_findings = [f for f in findings if 'MANUAL' in str(f.get('status', '')).upper() or 'manual' in str(f.get('detail', '')).lower() or 'manual' in str(f.get('evidence', '')).lower()]
    priority_findings = [f for f in failed_findings if str(f.get('severity', '')).upper() in ['CRITICAL', 'HIGH']]

    # Total width = 508.87 pt
    CONTENT_WIDTH = 508.87

    # ---------------------------------------------------------
    # COVER PAGE
    # ---------------------------------------------------------
    story.append(Spacer(1, 20))
    story.append(Paragraph("SSDLC ANALYZER", ParagraphStyle('CoverEyebrow', fontName='Helvetica-Bold', fontSize=10, textColor=colors.HexColor('#475569'), spaceAfter=8)))
    story.append(Paragraph("SECURITY ASSESSMENT REPORT", doc_title_style))
    story.append(Paragraph("Secure Software Development Lifecycle Audit & Risk Analysis", doc_subtitle_style))
    story.append(HRFlowable(width="100%", thickness=1.5, color=colors.HexColor('#0F172A'), spaceAfter=18))

    meta_rows = [
        [Paragraph("<b>Target Project / Repository:</b>", body_style), Paragraph(format_text(project_name), body_style)],
        [Paragraph("<b>Assessment Timestamp:</b>", body_style), Paragraph(format_text(started_at), body_style)],
        [Paragraph("<b>Assessment Type:</b>", body_style), Paragraph("SSDLC Maturity & Security Controls Evaluation", body_style)],
        [Paragraph("<b>Assessment Engine:</b>", body_style), Paragraph("SSDLC Analyzer Core v2.0.0 (Semgrep + Gitleaks)", body_style)],
        [Paragraph("<b>Unique Scan ID:</b>", body_style), Paragraph(format_text(scan_id), body_style)],
        [Paragraph("<b>Document Classification:</b>", body_style), Paragraph("CONFIDENTIAL / INTERNAL TECHNICAL AUDIT REPORT", body_style)],
    ]
    meta_tbl = Table(meta_rows, colWidths=[150, 358.87])
    meta_tbl.setStyle(TableStyle([
        ('LINEBELOW', (0, 0), (-1, -1), 0.5, colors.HexColor('#F1F5F9')),
        ('PADDING', (0, 0), (-1, -1), 6),
    ]))
    story.append(meta_tbl)
    story.append(Spacer(1, 24))
    story.append(HRFlowable(width="100%", thickness=0.5, color=colors.HexColor('#CBD5E1'), spaceAfter=20))

    # Cover Posture Summary Block
    cover_posture_html = f"""
    <font size=9 color="#475569">OVERALL SECURITY POSTURE SCORE</font><br/><br/>
    <font size=34 color="{risk_info['color']}"><b>{int(round(score))}</b></font><font size=16 color="#64748B"> / 100</font><br/><br/>
    <font size=12 color="{risk_info['color']}"><b>RISK CLASSIFICATION: {risk_info['label']}</b></font><br/>
    <font size=8.5 color="#334155">{risk_info['desc']}</font>
    """
    posture_tbl = Table([[Paragraph(cover_posture_html, ParagraphStyle('CoverPosture', parent=styles['Normal'], leading=14))]], colWidths=[CONTENT_WIDTH])
    posture_tbl.setStyle(TableStyle([
        ('BACKGROUND', (0, 0), (-1, -1), colors.HexColor('#F8FAFC')),
        ('BORDER', (0, 0), (-1, -1), 0.5, colors.HexColor('#E2E8F0')),
        ('PADDING', (0, 0), (-1, -1), 16),
    ]))
    story.append(posture_tbl)
    story.append(Spacer(1, 40))

    story.append(Paragraph("<b>Notice:</b> This document contains automated and heuristic security evaluation findings. Information contained herein is intended strictly for project owners, lead engineers, and security auditors.", ParagraphStyle('CoverNotice', parent=body_style, fontSize=8, textColor=colors.HexColor('#64748B'))))
    story.append(PageBreak())

    # ---------------------------------------------------------
    # PAGE 2: TABLE OF CONTENTS
    # ---------------------------------------------------------
    story.append(Paragraph("TABLE OF CONTENTS", h1_style))
    story.append(HRFlowable(width="100%", thickness=1, color=colors.HexColor('#0F172A'), spaceAfter=14))

    toc_items = [
        ("01", "Executive Summary & Key Metrics", "03"),
        ("02", "Security Posture Scale & Evaluation Tiers", "03"),
        ("03", "SSDLC Domain Assessment Breakdown", "04"),
        ("04", "Priority Findings (Critical & High Triage)", "05"),
        ("05", "Complete Vulnerability & Control Register", "06"),
        ("06", "Passed Security Controls Register", "10"),
        ("07", "Skipped Checks Register", "11"),
        ("08", "Manual Verification Required Items", "12"),
        ("09", "Practical Remediation Plan & Roadmap", "13"),
        ("10", "Methodology & Assessment Scope", "14"),
        ("11", "Tooling Inventory & Technical Limitations", "15"),
        ("12", "Final Security Assessment Recap", "16"),
    ]

    toc_rows = []
    for num, title, pg in toc_items:
        dots_count = max(5, 55 - len(title))
        dots = "." * dots_count
        toc_rows.append([
            Paragraph(f"<b>{num}</b>", tbl_head_style),
            Paragraph(f"{title} <font color='#94A3B8'>{dots}</font>", tbl_cell_style),
            Paragraph(f"<b>{pg}</b>", tbl_head_style),
        ])

    toc_tbl = Table(toc_rows, colWidths=[30, 438.87, 40])
    toc_tbl.setStyle(TableStyle([
        ('LINEBELOW', (0, 0), (-1, -1), 0.5, colors.HexColor('#F8FAFC')),
        ('PADDING', (0, 0), (-1, -1), 7),
        ('VALIGN', (0, 0), (-1, -1), 'MIDDLE'),
    ]))
    story.append(toc_tbl)
    story.append(PageBreak())

    # ---------------------------------------------------------
    # SECTION 01: EXECUTIVE SUMMARY
    # ---------------------------------------------------------
    story.append(Paragraph("01", section_num_style))
    story.append(Paragraph("EXECUTIVE SUMMARY", h1_style))
    story.append(HRFlowable(width="100%", thickness=1, color=colors.HexColor('#0F172A'), spaceAfter=10))

    summary_p = f"""
    This Security Assessment Report evaluates the secure software development lifecycle posture of <b>{format_text(project_name)}</b>.
    The automated analyzer evaluated controls across 6 core SSDLC security domains, arriving at an overall score of
    <b>{int(round(score))}/100</b>, which places the target project in the <b>{risk_info['label']}</b> tier.
    """
    story.append(Paragraph(summary_p, body_style))
    story.append(Spacer(1, 8))

    total_checks = summary.get('total_checks', len(findings))
    passed_cnt = summary.get('passed', len(passed_findings))
    failed_cnt = summary.get('failed', len(failed_findings))
    skipped_cnt = summary.get('skipped', len(skipped_findings))

    crit_cnt = summary.get('critical', 0)
    high_cnt = summary.get('high', 0)
    med_cnt = summary.get('medium', 0)
    low_cnt = summary.get('low', 0)

    exec_grid = [
        [
            Paragraph("<b>Assessment Metric</b>", tbl_head_style),
            Paragraph("<b>Result / Value</b>", tbl_head_style),
            Paragraph("<b>Audit Interpretation</b>", tbl_head_style),
        ],
        [Paragraph("Overall Posture Score", tbl_cell_style), Paragraph(f"<b>{int(round(score))} / 100</b>", tbl_cell_style), Paragraph(f"<font color='{risk_info['color']}'><b>{risk_info['label']}</b></font>", tbl_cell_style)],
        [Paragraph("Total Controls Assessed", tbl_cell_style), Paragraph(str(total_checks), tbl_cell_style), Paragraph("Exhaustive checks executed across codebase", tbl_cell_style)],
        [Paragraph("Passed Security Controls", tbl_cell_style), Paragraph(f"<font color='#15803D'><b>{passed_cnt}</b></font>", tbl_cell_style), Paragraph("Meeting defined security baseline criteria", tbl_cell_style)],
        [Paragraph("Controls Requiring Attention", tbl_cell_style), Paragraph(f"<font color='#B91C1C'><b>{failed_cnt}</b></font>", tbl_cell_style), Paragraph("Deficiencies requiring engineering remediation", tbl_cell_style)],
        [Paragraph("Skipped Checks", tbl_cell_style), Paragraph(str(skipped_cnt), tbl_cell_style), Paragraph("No matching tech stack or framework detected", tbl_cell_style)],
    ]
    exec_tbl = Table(exec_grid, colWidths=[160, 100, 248.87])
    exec_tbl.setStyle(TableStyle([
        ('BACKGROUND', (0, 0), (-1, 0), colors.HexColor('#F8FAFC')),
        ('GRID', (0, 0), (-1, -1), 0.5, colors.HexColor('#E2E8F0')),
        ('PADDING', (0, 0), (-1, -1), 6),
    ]))
    story.append(exec_tbl)
    story.append(Spacer(1, 10))

    story.append(Paragraph("<b>Deficiencies Breakdown by Severity:</b>", body_bold))
    story.append(Spacer(1, 4))
    
    sev_rows = [
        [
            Paragraph("<b>CRITICAL</b>", tbl_head_style),
            Paragraph("<b>HIGH</b>", tbl_head_style),
            Paragraph("<b>MEDIUM</b>", tbl_head_style),
            Paragraph("<b>LOW</b>", tbl_head_style),
            Paragraph("<b>MANUAL REVIEW</b>", tbl_head_style),
        ],
        [
            Paragraph(f"<font color='#B91C1C'><b>{crit_cnt}</b></font>", tbl_cell_style),
            Paragraph(f"<font color='#C2410C'><b>{high_cnt}</b></font>", tbl_cell_style),
            Paragraph(f"<font color='#B45309'><b>{med_cnt}</b></font>", tbl_cell_style),
            Paragraph(f"<font color='#1D4ED8'><b>{low_cnt}</b></font>", tbl_cell_style),
            Paragraph(f"<b>{len(manual_findings)}</b>", tbl_cell_style),
        ]
    ]
    sev_tbl = Table(sev_rows, colWidths=[101.77]*5)
    sev_tbl.setStyle(TableStyle([
        ('BACKGROUND', (0, 0), (-1, 0), colors.HexColor('#F1F5F9')),
        ('GRID', (0, 0), (-1, -1), 0.5, colors.HexColor('#CBD5E1')),
        ('PADDING', (0, 0), (-1, -1), 5),
        ('ALIGN', (0, 0), (-1, -1), 'CENTER'),
    ]))
    story.append(sev_tbl)
    story.append(Spacer(1, 14))

    # ---------------------------------------------------------
    # SECTION 02: SECURITY POSTURE & SCORE SCALE
    # ---------------------------------------------------------
    story.append(Paragraph("02", section_num_style))
    story.append(Paragraph("SECURITY POSTURE & EVALUATION SCALE", h1_style))
    story.append(HRFlowable(width="100%", thickness=1, color=colors.HexColor('#0F172A'), spaceAfter=10))

    scale_ascii = f"""
    SCORE SCALE:   0 ---------- 25 ---------- 50 ---------- 75 ---------- 100
                   [  CRITICAL  ]  [   HIGH   ]  [ MODERATE ]  [   LOW    ]
                                        ▲
                         YOUR PROJECT SCORE: {int(round(score))} / 100 ({risk_info['label']})
    """
    story.append(Paragraph(scale_ascii, mono_style))
    story.append(Spacer(1, 6))

    tier_rows = [
        [Paragraph("<b>Score Range</b>", tbl_head_style), Paragraph("<b>Posture Tier</b>", tbl_head_style), Paragraph("<b>Maturity Description</b>", tbl_head_style)],
        [Paragraph("80 – 100", tbl_cell_style), Paragraph("<font color='#15803D'><b>LOW RISK</b></font>", tbl_cell_style), Paragraph("Strong baseline security controls verified across majority of domains.", tbl_cell_style)],
        [Paragraph("60 – 79", tbl_cell_style), Paragraph("<font color='#B45309'><b>MODERATE RISK</b></font>", tbl_cell_style), Paragraph("Adequate baseline, but key security controls require remediation.", tbl_cell_style)],
        [Paragraph("40 – 59", tbl_cell_style), Paragraph("<font color='#C2410C'><b>HIGH RISK</b></font>", tbl_cell_style), Paragraph("Significant control failures; vulnerabilities present across core domains.", tbl_cell_style)],
        [Paragraph("0 – 39", tbl_cell_style), Paragraph("<font color='#B91C1C'><b>CRITICAL RISK</b></font>", tbl_cell_style), Paragraph("Severe security deficiencies; immediate technical remediation required.", tbl_cell_style)],
    ]
    tier_tbl = Table(tier_rows, colWidths=[90, 110, 308.87])
    tier_tbl.setStyle(TableStyle([
        ('GRID', (0, 0), (-1, -1), 0.5, colors.HexColor('#E2E8F0')),
        ('PADDING', (0, 0), (-1, -1), 5),
    ]))
    story.append(tier_tbl)
    story.append(Spacer(1, 14))

    # ---------------------------------------------------------
    # SECTION 03: SSDLC DOMAIN ASSESSMENT
    # ---------------------------------------------------------
    story.append(Paragraph("03", section_num_style))
    story.append(Paragraph("SSDLC DOMAIN ASSESSMENT", h1_style))
    story.append(HRFlowable(width="100%", thickness=1, color=colors.HexColor('#0F172A'), spaceAfter=10))

    domain_headers = [
        Paragraph("<b>#</b>", tbl_head_style),
        Paragraph("<b>SSDLC Domain</b>", tbl_head_style),
        Paragraph("<b>Weight</b>", tbl_head_style),
        Paragraph("<b>Passed / Total</b>", tbl_head_style),
        Paragraph("<b>Pass %</b>", tbl_head_style),
        Paragraph("<b>Domain Status</b>", tbl_head_style),
    ]
    domain_rows = [domain_headers]

    for idx, d in enumerate(domains, 1):
        d_name = d.get('domain', 'Domain')
        d_weight = f"{int(round(float(d.get('weight', 0)) * 100))}%"
        d_passed = d.get('passed', 0)
        d_total = d.get('total', 0)
        d_score = float(d.get('score', 0))
        d_status = get_domain_status(d_score)

        domain_rows.append([
            Paragraph(f"0{idx}", tbl_cell_style),
            Paragraph(f"<b>{format_text(d_name)}</b>", tbl_cell_style),
            Paragraph(d_weight, tbl_cell_style),
            Paragraph(f"{d_passed} / {d_total}", tbl_cell_style),
            Paragraph(f"<b>{int(round(d_score))}%</b>", tbl_cell_style),
            Paragraph(f"<font color='{d_status['color']}'><b>{d_status['label']}</b></font>", tbl_cell_style),
        ])

    domain_tbl = Table(domain_rows, colWidths=[25, 145, 55, 90, 65, 128.87], repeatRows=1)
    domain_tbl.setStyle(TableStyle([
        ('BACKGROUND', (0, 0), (-1, 0), colors.HexColor('#0F172A')),
        ('TEXTCOLOR', (0, 0), (-1, 0), colors.HexColor('#FFFFFF')),
        ('GRID', (0, 0), (-1, -1), 0.5, colors.HexColor('#CBD5E1')),
        ('PADDING', (0, 0), (-1, -1), 6),
        ('VALIGN', (0, 0), (-1, -1), 'MIDDLE'),
    ]))
    story.append(domain_tbl)
    story.append(Spacer(1, 14))

    # ---------------------------------------------------------
    # SECTION 04: PRIORITY FINDINGS
    # ---------------------------------------------------------
    if priority_findings:
        story.append(Paragraph("04", section_num_style))
        story.append(Paragraph("PRIORITY FINDINGS (CRITICAL & HIGH TRIAGE)", h1_style))
        story.append(HRFlowable(width="100%", thickness=1, color=colors.HexColor('#0F172A'), spaceAfter=10))

        p_rows = [[
            Paragraph("<b>ID</b>", tbl_head_style),
            Paragraph("<b>Severity</b>", tbl_head_style),
            Paragraph("<b>Control Finding Name</b>", tbl_head_style),
            Paragraph("<b>SSDLC Domain</b>", tbl_head_style),
        ]]
        for idx, pf in enumerate(priority_findings, 1):
            fid = f"P-{idx:03d}"
            sev = str(pf.get('severity', 'HIGH')).upper()
            sev_color = "#B91C1C" if sev == 'CRITICAL' else "#C2410C"
            p_rows.append([
                Paragraph(fid, tbl_cell_style),
                Paragraph(f"<font color='{sev_color}'><b>{sev}</b></font>", tbl_cell_style),
                Paragraph(f"<b>{format_text(pf.get('name', 'Finding'))}</b>", tbl_cell_style),
                Paragraph(format_text(pf.get('domain', '')), tbl_cell_style),
            ])

        p_tbl = Table(p_rows, colWidths=[55, 75, 240, 138.87], repeatRows=1)
        p_tbl.setStyle(TableStyle([
            ('BACKGROUND', (0, 0), (-1, 0), colors.HexColor('#FEF2F2')),
            ('GRID', (0, 0), (-1, -1), 0.5, colors.HexColor('#FCA5A5')),
            ('PADDING', (0, 0), (-1, -1), 5),
        ]))
        story.append(p_tbl)
        story.append(Spacer(1, 14))

    # ---------------------------------------------------------
    # SECTION 05: COMPLETE VULNERABILITY REGISTER
    # ---------------------------------------------------------
    story.append(Paragraph("05", section_num_style))
    story.append(Paragraph("COMPLETE VULNERABILITY & CONTROL REGISTER", h1_style))
    story.append(HRFlowable(width="100%", thickness=1, color=colors.HexColor('#0F172A'), spaceAfter=10))

    if not failed_findings:
        story.append(Paragraph("<font color='#15803D'><b>No security control failures identified. Excellent security posture!</b></font>", body_style))
    else:
        for idx, f in enumerate(failed_findings, 1):
            fid = f"F-{idx:03d}"
            fname = format_text(f.get('name', 'Control Finding'))
            fdomain = format_text(f.get('domain', 'General'))
            fsev = str(f.get('severity', 'MEDIUM')).upper() if f.get('severity') else 'MEDIUM'
            fdetail = format_text(f.get('detail', f.get('description', 'Control check failed.')))
            fevidence = format_text(f.get('evidence', ''))
            fremediation = format_text(f.get('remediation', 'Implement required control.'))

            sev_color = {
                'CRITICAL': '#B91C1C',
                'HIGH': '#C2410C',
                'MEDIUM': '#B45309',
                'LOW': '#1D4ED8',
                'INFO': '#475569'
            }.get(fsev, '#475569')

            header_html = f"<b>{fid} | {fname.upper()}</b>"
            meta_line = f"Domain: <b>{fdomain}</b> &nbsp;|&nbsp; Severity: <font color='{sev_color}'><b>{fsev}</b></font> &nbsp;|&nbsp; Status: <font color='#B91C1C'><b>FAIL</b></font>"

            block_elements = [
                HRFlowable(width="100%", thickness=0.5, color=colors.HexColor('#CBD5E1'), spaceAfter=6, spaceBefore=4),
                Paragraph(header_html, h2_style),
                Paragraph(meta_line, ParagraphStyle('MetaLine', parent=body_style, textColor=colors.HexColor('#475569'))),
                Spacer(1, 4),
                Paragraph(f"<b>DESCRIPTION &amp; DETAILS:</b><br/>{fdetail}", body_style),
            ]

            if fevidence:
                block_elements.append(Paragraph("<b>TECHNICAL EVIDENCE:</b>", body_bold))
                block_elements.append(Paragraph(fevidence, mono_style))

            if fremediation:
                block_elements.append(Paragraph(f"<b>RECOMMENDED REMEDIATION:</b><br/>{fremediation}", body_style))

            block_elements.append(Spacer(1, 6))
            story.append(KeepTogether(block_elements))

    # ---------------------------------------------------------
    # SECTION 06: PASSED SECURITY CONTROLS
    # ---------------------------------------------------------
    story.append(Spacer(1, 10))
    story.append(Paragraph("06", section_num_style))
    story.append(Paragraph("PASSED SECURITY CONTROLS", h1_style))
    story.append(HRFlowable(width="100%", thickness=1, color=colors.HexColor('#0F172A'), spaceAfter=10))

    if passed_findings:
        pass_rows = [[
            Paragraph("<b>Control Check Name</b>", tbl_head_style),
            Paragraph("<b>Domain</b>", tbl_head_style),
            Paragraph("<b>Status</b>", tbl_head_style),
            Paragraph("<b>Evidence Summary</b>", tbl_head_style),
        ]]
        for pf in passed_findings:
            pass_rows.append([
                Paragraph(f"<b>{format_text(pf.get('name', ''))}</b>", tbl_cell_style),
                Paragraph(format_text(pf.get('domain', '')), tbl_cell_style),
                Paragraph("<font color='#15803D'><b>PASS</b></font>", tbl_cell_style),
                Paragraph(format_text(pf.get('detail', 'Verified meeting expected security criteria.')), tbl_cell_style),
            ])
        pass_tbl = Table(pass_rows, colWidths=[150, 95, 55, 208.87], repeatRows=1)
        pass_tbl.setStyle(TableStyle([
            ('BACKGROUND', (0, 0), (-1, 0), colors.HexColor('#F0FDF4')),
            ('GRID', (0, 0), (-1, -1), 0.5, colors.HexColor('#DCFCE7')),
            ('PADDING', (0, 0), (-1, -1), 5),
        ]))
        story.append(pass_tbl)
    else:
        story.append(Paragraph("No controls currently marked as passed.", body_style))

    story.append(Spacer(1, 14))

    # ---------------------------------------------------------
    # SECTION 07 & 08: SKIPPED & MANUAL VERIFICATION
    # ---------------------------------------------------------
    story.append(Paragraph("07", section_num_style))
    story.append(Paragraph("SKIPPED CONTROLS", h1_style))
    story.append(HRFlowable(width="100%", thickness=1, color=colors.HexColor('#0F172A'), spaceAfter=10))

    if skipped_findings:
        skip_rows = [[
            Paragraph("<b>Control Check Name</b>", tbl_head_style),
            Paragraph("<b>Domain</b>", tbl_head_style),
            Paragraph("<b>Status</b>", tbl_head_style),
            Paragraph("<b>Reason / Details</b>", tbl_head_style),
        ]]
        for sf in skipped_findings:
            skip_rows.append([
                Paragraph(format_text(sf.get('name', '')), tbl_cell_style),
                Paragraph(format_text(sf.get('domain', '')), tbl_cell_style),
                Paragraph("<font color='#475569'><b>SKIPPED</b></font>", tbl_cell_style),
                Paragraph(format_text(sf.get('detail', 'No matching framework or tech stack detected.')), tbl_cell_style),
            ])
        skip_tbl = Table(skip_rows, colWidths=[150, 95, 65, 198.87], repeatRows=1)
        skip_tbl.setStyle(TableStyle([
            ('BACKGROUND', (0, 0), (-1, 0), colors.HexColor('#F8FAFC')),
            ('GRID', (0, 0), (-1, -1), 0.5, colors.HexColor('#E2E8F0')),
            ('PADDING', (0, 0), (-1, -1), 5),
        ]))
        story.append(skip_tbl)
    else:
        story.append(Paragraph("No controls were skipped during this scan.", body_style))

    story.append(Spacer(1, 14))

    story.append(Paragraph("08", section_num_style))
    story.append(Paragraph("MANUAL VERIFICATION REQUIRED", h1_style))
    story.append(HRFlowable(width="100%", thickness=1, color=colors.HexColor('#0F172A'), spaceAfter=10))

    manual_note = """
    <b>Formal Security Audit Note:</b> Certain security controls cannot be conclusively verified strictly through local static code analysis alone.
    For instance, <b>Branch Protection Rules</b> or <b>Git Hosting Provider API Access Restrictions</b> require manual verification in hosting provider settings.
    <br/><br/>
    <b>Recommended Manual Verification Protocol:</b>
    Confirm that the primary repository branch mandates:
    1. Mandatory Pull Request reviews prior to merging.
    2. Passing automated CI/CD status checks.
    3. Restricted direct push access to protected branches.
    """
    story.append(Paragraph(manual_note, body_style))
    story.append(Spacer(1, 14))

    # ---------------------------------------------------------
    # SECTION 09: REMEDIATION PLAN & ROADMAP
    # ---------------------------------------------------------
    story.append(Paragraph("09", section_num_style))
    story.append(Paragraph("PRACTICAL REMEDIATION PLAN & ROADMAP", h1_style))
    story.append(HRFlowable(width="100%", thickness=1, color=colors.HexColor('#0F172A'), spaceAfter=10))

    road_rows = [
        [
            Paragraph("<b>Priority</b>", tbl_head_style),
            Paragraph("<b>Target Deficiency / Gap</b>", tbl_head_style),
            Paragraph("<b>Actionable Remediation Steps</b>", tbl_head_style),
            Paragraph("<b>Expected Security Outcome</b>", tbl_head_style),
        ],
        [
            Paragraph("<font color='#B91C1C'><b>Priority 1</b><br/>IMMEDIATE</font>", tbl_cell_style),
            Paragraph("Critical / High Vulnerabilities & Missing CI Checks", tbl_cell_style),
            Paragraph("1. Purge any hardcoded secrets.<br/>2. Add automated CI security scanner pipeline.", tbl_cell_style),
            Paragraph("Prevents credential exposure and enforces automated code security checks.", tbl_cell_style),
        ],
        [
            Paragraph("<font color='#B45309'><b>Priority 2</b><br/>SHORT TERM</font>", tbl_cell_style),
            Paragraph("Medium Severity Controls & Documentation Gaps", tbl_cell_style),
            Paragraph("1. Formally document security requirements.<br/>2. Configure SAST rules.", tbl_cell_style),
            Paragraph("Establishes clear architecture guidelines and code guardrails.", tbl_cell_style),
        ],
        [
            Paragraph("<font color='#1D4ED8'><b>Priority 3</b><br/>ONGOING</font>", tbl_cell_style),
            Paragraph("Low Severity Items & Dependency Tracking", tbl_cell_style),
            Paragraph("1. Routinely update external dependencies.<br/>2. Expand security test suites.", tbl_cell_style),
            Paragraph("Maintains long-term software supply chain hygiene.", tbl_cell_style),
        ],
    ]
    road_tbl = Table(road_rows, colWidths=[85, 135, 160, 128.87], repeatRows=1)
    road_tbl.setStyle(TableStyle([
        ('BACKGROUND', (0, 0), (-1, 0), colors.HexColor('#F1F5F9')),
        ('GRID', (0, 0), (-1, -1), 0.5, colors.HexColor('#CBD5E1')),
        ('PADDING', (0, 0), (-1, -1), 5),
        ('VALIGN', (0, 0), (-1, -1), 'TOP'),
    ]))
    story.append(road_tbl)
    story.append(Spacer(1, 14))

    # ---------------------------------------------------------
    # SECTION 10 & 11: METHODOLOGY & LIMITATIONS
    # ---------------------------------------------------------
    story.append(Paragraph("10", section_num_style))
    story.append(Paragraph("METHODOLOGY & ASSESSMENT SCOPE", h1_style))
    story.append(HRFlowable(width="100%", thickness=1, color=colors.HexColor('#0F172A'), spaceAfter=10))

    meth_p = """
    <b>Assessment Framework:</b> SSDLC Analyzer evaluates codebases against 6 core security domains: Requirements, Architecture, Implementation, Testing, Supply Chain, and Lifecycle.
    The analyzer utilizes static application security testing (Semgrep), secret detection (Gitleaks), and native repository heuristics.
    Controls are classified into <i>AUTOMATED</i>, <i>SKIPPED</i>, and <i>MANUAL VERIFICATION REQUIRED</i>.
    """
    story.append(Paragraph(meth_p, body_style))
    story.append(Spacer(1, 14))

    story.append(Paragraph("11", section_num_style))
    story.append(Paragraph("TOOLING INVENTORY & TECHNICAL LIMITATIONS", h1_style))
    story.append(HRFlowable(width="100%", thickness=1, color=colors.HexColor('#0F172A'), spaceAfter=10))

    tool_p = """
    <b>Tooling Inventory:</b> SSDLC Analyzer Engine v2.0.0, Semgrep SAST Engine, Gitleaks Secret Scanner.
    <br/><br/>
    <b>Technical Boundaries Disclaimer:</b> Static analysis evaluates source code artefacts available within the target repository repository archive.
    It cannot assess live cloud infrastructure configurations, active firewall rules, dynamic runtime responses, or Git hosting platform API settings.
    Absence of evidence within static code does not guarantee absence of control.
    """
    story.append(Paragraph(tool_p, body_style))
    story.append(Spacer(1, 14))

    # ---------------------------------------------------------
    # SECTION 12: FINAL SECURITY ASSESSMENT RECAP
    # ---------------------------------------------------------
    story.append(Paragraph("12", section_num_style))
    story.append(Paragraph("FINAL SECURITY ASSESSMENT RECAP", h1_style))
    story.append(HRFlowable(width="100%", thickness=1, color=colors.HexColor('#0F172A'), spaceAfter=10))

    recap_html = f"""
    <b>Final Score:</b> {int(round(score))}/100 &nbsp;|&nbsp;
    <b>Classification:</b> <font color="{risk_info['color']}"><b>{risk_info['label']}</b></font> &nbsp;|&nbsp;
    <b>Passed Controls:</b> {passed_cnt} &nbsp;|&nbsp;
    <b>Requiring Attention:</b> {failed_cnt}
    <br/><br/>
    <i>This document constitutes the official technical assessment record for Scan ID <b>{format_text(scan_id)}</b>.</i>
    """
    story.append(Paragraph(recap_html, body_style))

    # Build Document
    doc.build(story, canvasmaker=NumberedCanvas)
    buffer.seek(0)
    return buffer.getvalue()
